project:
  type: website
  output-dir: docs

# Website options
#################
website:
  # True website title displayed on browser tabs, in searches, etc.
  title: Tobias M. Holden 
  favicon: images/tmh_logo.png
  page-footer: "© Tobias M. Holden 2023"
  # Website Navigation
  ####################
  sidebar:
    # Sidebar style options 
    style: floating     # "floating" or "docked"
    foreground: light   # sidebar text color
    background: primary # sidebar background color
    # Top
    logo: images/tmh_logo_white.png
    title: Tobias M. Holden
    header: ""    
    # Social / scholar links in sidebar
    ###################################
    tools: 
      - icon: twitter
        text: twitter
        href: https://twitter.com/tobiasmholden
      - icon: linkedin
        text: linkedin
        href: www.linkedin.com/in/tobiasholden1017
      - icon: github
        text: github
        href: https://github.com/tobias-holden
      - icon: mortarboard-fill
        text: scholar
        href: https://scholar.google.com/citations?user=wK3JrXUAAAAJ&hl=en
    search: true        # include site-wide search?
    # Sidebar Contents
    ##################
    # Shows only the index.qmd by default
    contents: 
      - text: "CURRICULUM VITAE"
        href: cv.qmd
      - section: "Blogs"
        contents: blogs/*.qmd
            
# Theme Options
###############
format:
  html:
    page-layout: full
    theme: pulse        # more theme options @ https://bootswatch.com/
    css: styles.css

editor: visual