---
title: ""
title-block-style: default
listing:
  - id: my-education
    type: grid
    fields: [title, description, author, image]
    image-height: "1cm"
    sort: "description-desc"
    contents: my_education/*.qmd   # this will list every experience.qmd in the my_education folder
    grid-columns: 3
    page-size: 3
    
  - id: my-research
    type: grid
    grid-columns: 3
    page-size: 3
    contents: my_research/*.qmd   # this will list every experience.qmd in the my_research folder
    fields: [title, description, author, image]
    image-placeholder: images/light_purple.png
    image-height: "1cm"
    field-display-names: 
      author: "Location"
    sort: 
      - "current desc"
      - "description desc"
      
  - id: my-publication-list
    type: table
    table-striped: true
    table-hover: true
    contents: my_publications/*.qmd 
    page-size: 3
    fields: [date, title, journal-name, citations]
    field-display-names: 
      journal-name: "Journal"
      date: "Year"
      citations: "Cites"
    filter-ui: false
    sort-ui: false
    date-format: "YYYY"
    sort: "date desc"
    
  - id: my-oral-presentation-list
    type: table
    table-striped: true
    table-hover: true
    contents: my_presentations/oral_presentations/*.qmd
    fields: [year, title, conference-event]
    filter-ui: false
    sort-ui: false
    sort: "year desc"
    page-size: 3
    field-display-names: 
      conference-event: "Conference/Event"
      year: "Year"
        
  - id: my-poster-presentation-list
    type: table
    table-striped: true
    table-hover: true
    contents: my_presentations/poster_presentations/*.qmd
    fields: [year, title, conference-event]
    filter-ui: false
    sort-ui: false
    page-size: 3
    sort: "year desc"
    field-display-names: 
      conference-event: "Conference/Event"
      year: "Year"
  
  - id: my-grants-and-fellowships
    contents: grants_and_fellowships/*.qmd
    type: table
    page-size: 3
    sort-ui: false
    filter-ui: false
    fields: [years, type, title, description]
    field-display-names: 
      years: "Year(s)"
      title: "Grant or Fellowship"
      type: "Type"
      description: "Source"
    sort: "years desc"
    
  - id: my-awards-and-honors
    contents: 
      - awards_and_honors/*.qmd
    type: table
    fields: [years, title, description]
    field-display-names: 
      title: "Award or Honor"
      years: "Year(s)"
      description: "Source"
    sort-ui: false
    filter-ui: false
    sort: "years desc"
    page-size: 3
    
  - id: all-my-activities
    contents: 
      - teaching_and_mentoring/*.qmd
      - extracurricular/*.qmd
    type: table
    fields: [years, type, title, description]
    field-display-names: 
      years: "Year(s)"
      type: "Category"
      title: "Role"
      description: " "
    sort: 
      - "current desc"
      - "years desc"
    page-size: 3
    filter-ui: false
    sort-ui: false

format: 
  html: 
    page-layout: article
    toc: false
---

<center>

<h1>

Tobias M. Holden

------------------------------------------------------------------------

</center>

</h1>

I am a MD/PhD student in the Northwestern University Medical Scientist Training Program. In my PhD research I have applied high-performance computing and mathematical modeling to study COVID-19 and malaria epidemiology. I am interested in using modeling and analytics to inform decision-making for public health.\
[[tobias.holden\@northwestern.edu](mailto:tobias.holden@northwestern.edu)]{.aside} [**Languages Spoken** <br> \| English (fluent) <br> \| Spanish (professional)]{.aside}

<center>

### [**Education**]{.smallcaps}

</center>

[**Non-Degree** <br> [NIH PREP \@ ISMMS](sinai_prep.qmd) (Postbac) <br> <br> **Pre-College** <br> SC Governor's School for Science and Mathematics]{.aside}

::: {#my-education}
:::

<center>

### [**Research**]{.smallcaps}

</center>

[**Skills** <br> \| Mathematical Modeling <br> \| GIS <br> \| High-Performance Computing <br> \| Biostatistics <br> \| Data Analysis <br> \| Data Visualization <br> \| App Development <br>]{.aside} [<br>**Programming Languages** <br> \| *R* <br> \| Python <br> \| Matlab <br> \| HTML <br> \| Linux]{.aside}

::: {#my-research}
:::

[<br> **Professional Affiliations** <br><br> \| [ACM Special Interest Group on High-Performance Computing](https://www.sighpc.org/) <br><br> \| [American Physician Scientists Association](https://www.physicianscientists.org/) <br><br> \| [American Society of Tropical Medicine & Hygiene](https://astmh.org) <br><br> \| [Applied Malaria Modeling Network](https://ammnetwork.org) <br><br> \| [Models of Infectious Disease Agent Study Network](https://midasnetwork.us/) <br><br> \| [NIH National Institute of Allergy and Infectious Disease](https://www.niaid.nih.gov/) <br><br> \| [NU Malaria Modeling](https://www.numalariamodeling.org/) <br><br> \| [NU Medical Scientist Training Program](https://www.feinberg.northwestern.edu/sites/mstp/)]{.aside}

::: panel-tabset
## Publications

::: {#my-publication-list}
:::

## Talks

::: {#my-oral-presentation-list}
:::

## Posters

::: {#my-poster-presentation-list}
:::
:::

<center>

### [**Activities & Awards**]{.smallcaps}

</center>

[<br> **Hobbies & Other Passions** <br> \| Film & Digital Photography <br> \| Hiking <br> \| Rollerblading <br> \| Trivia <br> \| Film Criticism]{.aside}

::: panel-tabset
## Grants & Fellowships

::: {#my-grants-and-fellowships}
:::

## Professional Activities

::: {#all-my-activities}
:::

## Awards & Honors

::: {#my-awards-and-honors}
:::
:::
